# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/common/proto/ceres_solver_options.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4cartographer/common/proto/ceres_solver_options.proto\x12\x19\x63\x61rtographer.common.proto\"e\n\x12\x43\x65resSolverOptions\x12\x1e\n\x16use_nonmonotonic_steps\x18\x01 \x01(\x08\x12\x1a\n\x12max_num_iterations\x18\x02 \x01(\x05\x12\x13\n\x0bnum_threads\x18\x03 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cartographer.common.proto.ceres_solver_options_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CERESSOLVEROPTIONS']._serialized_start=83
  _globals['_CERESSOLVEROPTIONS']._serialized_end=184
# @@protoc_insertion_point(module_scope)
