# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/cloud/proto/map_builder_server_options.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cartographer.mapping.proto import map_builder_options_pb2 as cartographer_dot_mapping_dot_proto_dot_map__builder__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9cartographer/cloud/proto/map_builder_server_options.proto\x12\x18\x63\x61rtographer.cloud.proto\x1a\x34\x63\x61rtographer/mapping/proto/map_builder_options.proto\"\xa7\x02\n\x17MapBuilderServerOptions\x12\x16\n\x0eserver_address\x18\x01 \x01(\t\x12\x18\n\x10num_grpc_threads\x18\x02 \x01(\x05\x12\x19\n\x11num_event_threads\x18\x03 \x01(\x05\x12J\n\x13map_builder_options\x18\x04 \x01(\x0b\x32-.cartographer.mapping.proto.MapBuilderOptions\x12\x1d\n\x15uplink_server_address\x18\x05 \x01(\t\x12\x19\n\x11upload_batch_size\x18\x06 \x01(\x05\x12\x1d\n\x15\x65nable_ssl_encryption\x18\x07 \x01(\x08\x12\x1a\n\x12\x65nable_google_auth\x18\t \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cartographer.cloud.proto.map_builder_server_options_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MAPBUILDERSERVEROPTIONS']._serialized_start=142
  _globals['_MAPBUILDERSERVEROPTIONS']._serialized_end=437
# @@protoc_insertion_point(module_scope)
