# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/pose_graph/constraint_builder_options.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cartographer.mapping.proto.scan_matching import ceres_scan_matcher_options_2d_pb2 as cartographer_dot_mapping_dot_proto_dot_scan__matching_dot_ceres__scan__matcher__options__2d__pb2
from cartographer.mapping.proto.scan_matching import ceres_scan_matcher_options_3d_pb2 as cartographer_dot_mapping_dot_proto_dot_scan__matching_dot_ceres__scan__matcher__options__3d__pb2
from cartographer.mapping.proto.scan_matching import fast_correlative_scan_matcher_options_2d_pb2 as cartographer_dot_mapping_dot_proto_dot_scan__matching_dot_fast__correlative__scan__matcher__options__2d__pb2
from cartographer.mapping.proto.scan_matching import fast_correlative_scan_matcher_options_3d_pb2 as cartographer_dot_mapping_dot_proto_dot_scan__matching_dot_fast__correlative__scan__matcher__options__3d__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nFcartographer/mapping/proto/pose_graph/constraint_builder_options.proto\x12&cartographer.mapping.constraints.proto\x1aLcartographer/mapping/proto/scan_matching/ceres_scan_matcher_options_2d.proto\x1aLcartographer/mapping/proto/scan_matching/ceres_scan_matcher_options_3d.proto\x1aWcartographer/mapping/proto/scan_matching/fast_correlative_scan_matcher_options_2d.proto\x1aWcartographer/mapping/proto/scan_matching/fast_correlative_scan_matcher_options_3d.proto\"\xc5\x05\n\x18\x43onstraintBuilderOptions\x12\x16\n\x0esampling_ratio\x18\x01 \x01(\x01\x12\x1f\n\x17max_constraint_distance\x18\x02 \x01(\x01\x12\x11\n\tmin_score\x18\x04 \x01(\x01\x12%\n\x1dglobal_localization_min_score\x18\x05 \x01(\x01\x12\'\n\x1floop_closure_translation_weight\x18\r \x01(\x01\x12$\n\x1cloop_closure_rotation_weight\x18\x0e \x01(\x01\x12\x13\n\x0blog_matches\x18\x08 \x01(\x08\x12|\n%fast_correlative_scan_matcher_options\x18\t \x01(\x0b\x32M.cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions2D\x12g\n\x1a\x63\x65res_scan_matcher_options\x18\x0b \x01(\x0b\x32\x43.cartographer.mapping.scan_matching.proto.CeresScanMatcherOptions2D\x12\x7f\n(fast_correlative_scan_matcher_options_3d\x18\n \x01(\x0b\x32M.cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions3D\x12j\n\x1d\x63\x65res_scan_matcher_options_3d\x18\x0c \x01(\x0b\x32\x43.cartographer.mapping.scan_matching.proto.CeresScanMatcherOptions3Db\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cartographer.mapping.proto.pose_graph.constraint_builder_options_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CONSTRAINTBUILDEROPTIONS']._serialized_start=449
  _globals['_CONSTRAINTBUILDEROPTIONS']._serialized_end=1158
# @@protoc_insertion_point(module_scope)
