# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/pose_graph/optimization_problem_options.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cartographer.common.proto import ceres_solver_options_pb2 as cartographer_dot_common_dot_proto_dot_ceres__solver__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nHcartographer/mapping/proto/pose_graph/optimization_problem_options.proto\x12\'cartographer.mapping.optimization.proto\x1a\x34\x63\x61rtographer/common/proto/ceres_solver_options.proto\"\x93\x05\n\x1aOptimizationProblemOptions\x12\x13\n\x0bhuber_scale\x18\x01 \x01(\x01\x12\x1b\n\x13\x61\x63\x63\x65leration_weight\x18\x08 \x01(\x01\x12\x17\n\x0frotation_weight\x18\t \x01(\x01\x12*\n\"local_slam_pose_translation_weight\x18\x0e \x01(\x01\x12\'\n\x1flocal_slam_pose_rotation_weight\x18\x0f \x01(\x01\x12#\n\x1bodometry_translation_weight\x18\x10 \x01(\x01\x12 \n\x18odometry_rotation_weight\x18\x11 \x01(\x01\x12+\n#fixed_frame_pose_translation_weight\x18\x0b \x01(\x01\x12(\n fixed_frame_pose_rotation_weight\x18\x0c \x01(\x01\x12*\n\"fixed_frame_pose_use_tolerant_loss\x18\x17 \x01(\x08\x12.\n&fixed_frame_pose_tolerant_loss_param_a\x18\x18 \x01(\x01\x12.\n&fixed_frame_pose_tolerant_loss_param_b\x18\x19 \x01(\x01\x12\x13\n\x0b\x66ix_z_in_3d\x18\r \x01(\x08\x12\'\n\x1fuse_online_imu_extrinsics_in_3d\x18\x12 \x01(\x08\x12\x1a\n\x12log_solver_summary\x18\x05 \x01(\x08\x12K\n\x14\x63\x65res_solver_options\x18\x07 \x01(\x0b\x32-.cartographer.common.proto.CeresSolverOptionsJ\x04\x08\x14\x10\x17\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cartographer.mapping.proto.pose_graph.optimization_problem_options_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_OPTIMIZATIONPROBLEMOPTIONS']._serialized_start=172
  _globals['_OPTIMIZATIONPROBLEMOPTIONS']._serialized_end=831
# @@protoc_insertion_point(module_scope)
