# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/ground_truth/proto/relations.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cartographer.transform.proto import transform_pb2 as cartographer_dot_transform_dot_proto_dot_transform__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/cartographer/ground_truth/proto/relations.proto\x12\x1f\x63\x61rtographer.ground_truth.proto\x1a,cartographer/transform/proto/transform.proto\"\x85\x01\n\x08Relation\x12\x12\n\ntimestamp1\x18\x01 \x01(\x03\x12\x12\n\ntimestamp2\x18\x02 \x01(\x03\x12\x37\n\x08\x65xpected\x18\x03 \x01(\x0b\x32%.cartographer.transform.proto.Rigid3d\x12\x18\n\x10\x63overed_distance\x18\x04 \x01(\x01\"J\n\x0bGroundTruth\x12;\n\x08relation\x18\x01 \x03(\x0b\x32).cartographer.ground_truth.proto.Relationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cartographer.ground_truth.proto.relations_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_RELATION']._serialized_start=131
  _globals['_RELATION']._serialized_end=264
  _globals['_GROUNDTRUTH']._serialized_start=266
  _globals['_GROUNDTRUTH']._serialized_end=340
# @@protoc_insertion_point(module_scope)
