# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/scan_matching/ceres_scan_matcher_options_2d.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cartographer.common.proto import ceres_solver_options_pb2 as cartographer_dot_common_dot_proto_dot_ceres__solver__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nLcartographer/mapping/proto/scan_matching/ceres_scan_matcher_options_2d.proto\x12(cartographer.mapping.scan_matching.proto\x1a\x34\x63\x61rtographer/common/proto/ceres_solver_options.proto\"\xbc\x01\n\x19\x43\x65resScanMatcherOptions2D\x12\x1d\n\x15occupied_space_weight\x18\x01 \x01(\x01\x12\x1a\n\x12translation_weight\x18\x02 \x01(\x01\x12\x17\n\x0frotation_weight\x18\x03 \x01(\x01\x12K\n\x14\x63\x65res_solver_options\x18\t \x01(\x0b\x32-.cartographer.common.proto.CeresSolverOptionsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cartographer.mapping.proto.scan_matching.ceres_scan_matcher_options_2d_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CERESSCANMATCHEROPTIONS2D']._serialized_start=177
  _globals['_CERESSCANMATCHEROPTIONS2D']._serialized_end=365
# @@protoc_insertion_point(module_scope)
