# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/scan_matching/ceres_scan_matcher_options_3d.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cartographer.common.proto import ceres_solver_options_pb2 as cartographer_dot_common_dot_proto_dot_ceres__solver__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nLcartographer/mapping/proto/scan_matching/ceres_scan_matcher_options_3d.proto\x12(cartographer.mapping.scan_matching.proto\x1a\x34\x63\x61rtographer/common/proto/ceres_solver_options.proto\"`\n\x1cIntensityCostFunctionOptions\x12\x0e\n\x06weight\x18\x01 \x01(\x01\x12\x13\n\x0bhuber_scale\x18\x02 \x01(\x01\x12\x1b\n\x13intensity_threshold\x18\x03 \x01(\x02\"\xc8\x02\n\x19\x43\x65resScanMatcherOptions3D\x12\x1d\n\x15occupied_space_weight\x18\x01 \x03(\x01\x12\x1a\n\x12translation_weight\x18\x02 \x01(\x01\x12\x17\n\x0frotation_weight\x18\x03 \x01(\x01\x12\x19\n\x11only_optimize_yaw\x18\x05 \x01(\x08\x12K\n\x14\x63\x65res_solver_options\x18\x06 \x01(\x0b\x32-.cartographer.common.proto.CeresSolverOptions\x12o\n\x1fintensity_cost_function_options\x18\x07 \x03(\x0b\x32\x46.cartographer.mapping.scan_matching.proto.IntensityCostFunctionOptionsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cartographer.mapping.proto.scan_matching.ceres_scan_matcher_options_3d_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_INTENSITYCOSTFUNCTIONOPTIONS']._serialized_start=176
  _globals['_INTENSITYCOSTFUNCTIONOPTIONS']._serialized_end=272
  _globals['_CERESSCANMATCHEROPTIONS3D']._serialized_start=275
  _globals['_CERESSCANMATCHEROPTIONS3D']._serialized_end=603
# @@protoc_insertion_point(module_scope)
