# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/scan_matching/fast_correlative_scan_matcher_options_3d.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nWcartographer/mapping/proto/scan_matching/fast_correlative_scan_matcher_options_3d.proto\x12(cartographer.mapping.scan_matching.proto\"\x84\x02\n#FastCorrelativeScanMatcherOptions3D\x12\x1e\n\x16\x62ranch_and_bound_depth\x18\x02 \x01(\x05\x12\x1d\n\x15\x66ull_resolution_depth\x18\x08 \x01(\x05\x12\x1c\n\x14min_rotational_score\x18\x04 \x01(\x01\x12 \n\x18min_low_resolution_score\x18\t \x01(\x01\x12\x1f\n\x17linear_xy_search_window\x18\x05 \x01(\x01\x12\x1e\n\x16linear_z_search_window\x18\x06 \x01(\x01\x12\x1d\n\x15\x61ngular_search_window\x18\x07 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cartographer.mapping.proto.scan_matching.fast_correlative_scan_matcher_options_3d_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_FASTCORRELATIVESCANMATCHEROPTIONS3D']._serialized_start=134
  _globals['_FASTCORRELATIVESCANMATCHEROPTIONS3D']._serialized_end=394
# @@protoc_insertion_point(module_scope)
