# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/scan_matching/real_time_correlative_scan_matcher_options.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nYcartographer/mapping/proto/scan_matching/real_time_correlative_scan_matcher_options.proto\x12(cartographer.mapping.scan_matching.proto\"\xaf\x01\n%RealTimeCorrelativeScanMatcherOptions\x12\x1c\n\x14linear_search_window\x18\x01 \x01(\x01\x12\x1d\n\x15\x61ngular_search_window\x18\x02 \x01(\x01\x12%\n\x1dtranslation_delta_cost_weight\x18\x03 \x01(\x01\x12\"\n\x1arotation_delta_cost_weight\x18\x04 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cartographer.mapping.proto.scan_matching.real_time_correlative_scan_matcher_options_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_REALTIMECORRELATIVESCANMATCHEROPTIONS']._serialized_start=136
  _globals['_REALTIMECORRELATIVESCANMATCHEROPTIONS']._serialized_end=311
# @@protoc_insertion_point(module_scope)
