# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/cell_limits_2d.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/cartographer/mapping/proto/cell_limits_2d.proto\x12\x1a\x63\x61rtographer.mapping.proto\"6\n\nCellLimits\x12\x13\n\x0bnum_x_cells\x18\x01 \x01(\x05\x12\x13\n\x0bnum_y_cells\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cartographer.mapping.proto.cell_limits_2d_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CELLLIMITS']._serialized_start=79
  _globals['_CELLLIMITS']._serialized_end=133
# @@protoc_insertion_point(module_scope)
