# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/connected_components.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5cartographer/mapping/proto/connected_components.proto\x12\x1a\x63\x61rtographer.mapping.proto\"\xa3\x01\n\x13\x43onnectedComponents\x12_\n\x13\x63onnected_component\x18\x01 \x03(\x0b\x32\x42.cartographer.mapping.proto.ConnectedComponents.ConnectedComponent\x1a+\n\x12\x43onnectedComponent\x12\x15\n\rtrajectory_id\x18\x01 \x03(\x05\x42\x1f\x42\x1d\x43onnectedComponentsOuterClassb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cartographer.mapping.proto.connected_components_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\035ConnectedComponentsOuterClass'
  _globals['_CONNECTEDCOMPONENTS']._serialized_start=86
  _globals['_CONNECTEDCOMPONENTS']._serialized_end=249
  _globals['_CONNECTEDCOMPONENTS_CONNECTEDCOMPONENT']._serialized_start=206
  _globals['_CONNECTEDCOMPONENTS_CONNECTEDCOMPONENT']._serialized_end=249
# @@protoc_insertion_point(module_scope)
