# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/grid_2d.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cartographer.mapping.proto import map_limits_pb2 as cartographer_dot_mapping_dot_proto_dot_map__limits__pb2
from cartographer.mapping.proto import probability_grid_pb2 as cartographer_dot_mapping_dot_proto_dot_probability__grid__pb2
from cartographer.mapping.proto import tsdf_2d_pb2 as cartographer_dot_mapping_dot_proto_dot_tsdf__2d__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(cartographer/mapping/proto/grid_2d.proto\x12\x1a\x63\x61rtographer.mapping.proto\x1a+cartographer/mapping/proto/map_limits.proto\x1a\x31\x63\x61rtographer/mapping/proto/probability_grid.proto\x1a(cartographer/mapping/proto/tsdf_2d.proto\"\xa7\x03\n\x06Grid2D\x12\x35\n\x06limits\x18\x01 \x01(\x0b\x32%.cartographer.mapping.proto.MapLimits\x12\r\n\x05\x63\x65lls\x18\x02 \x03(\x05\x12\x43\n\x0fknown_cells_box\x18\x03 \x01(\x0b\x32*.cartographer.mapping.proto.Grid2D.CellBox\x12J\n\x13probability_grid_2d\x18\x04 \x01(\x0b\x32+.cartographer.mapping.proto.ProbabilityGridH\x00\x12\x35\n\x07tsdf_2d\x18\x05 \x01(\x0b\x32\".cartographer.mapping.proto.TSDF2DH\x00\x12\x1f\n\x17min_correspondence_cost\x18\x06 \x01(\x02\x12\x1f\n\x17max_correspondence_cost\x18\x07 \x01(\x02\x1a\x45\n\x07\x43\x65llBox\x12\r\n\x05max_x\x18\x01 \x01(\x05\x12\r\n\x05max_y\x18\x02 \x01(\x05\x12\r\n\x05min_x\x18\x03 \x01(\x05\x12\r\n\x05min_y\x18\x04 \x01(\x05\x42\x06\n\x04gridb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cartographer.mapping.proto.grid_2d_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_GRID2D']._serialized_start=211
  _globals['_GRID2D']._serialized_end=634
  _globals['_GRID2D_CELLBOX']._serialized_start=557
  _globals['_GRID2D_CELLBOX']._serialized_end=626
# @@protoc_insertion_point(module_scope)
