# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/grid_2d_options.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0cartographer/mapping/proto/grid_2d_options.proto\x12\x1a\x63\x61rtographer.mapping.proto\"\xa8\x01\n\rGridOptions2D\x12\x45\n\tgrid_type\x18\x01 \x01(\x0e\x32\x32.cartographer.mapping.proto.GridOptions2D.GridType\x12\x12\n\nresolution\x18\x02 \x01(\x02\"<\n\x08GridType\x12\x10\n\x0cINVALID_GRID\x10\x00\x12\x14\n\x10PROBABILITY_GRID\x10\x01\x12\x08\n\x04TSDF\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cartographer.mapping.proto.grid_2d_options_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_GRIDOPTIONS2D']._serialized_start=81
  _globals['_GRIDOPTIONS2D']._serialized_end=249
  _globals['_GRIDOPTIONS2D_GRIDTYPE']._serialized_start=189
  _globals['_GRIDOPTIONS2D_GRIDTYPE']._serialized_end=249
# @@protoc_insertion_point(module_scope)
