# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/hybrid_grid.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,cartographer/mapping/proto/hybrid_grid.proto\x12\x1a\x63\x61rtographer.mapping.proto\"i\n\nHybridGrid\x12\x12\n\nresolution\x18\x01 \x01(\x02\x12\x11\n\tx_indices\x18\x03 \x03(\x11\x12\x11\n\ty_indices\x18\x04 \x03(\x11\x12\x11\n\tz_indices\x18\x05 \x03(\x11\x12\x0e\n\x06values\x18\x06 \x03(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cartographer.mapping.proto.hybrid_grid_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_HYBRIDGRID']._serialized_start=76
  _globals['_HYBRIDGRID']._serialized_end=181
# @@protoc_insertion_point(module_scope)
