# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/map_limits.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cartographer.mapping.proto import cell_limits_2d_pb2 as cartographer_dot_mapping_dot_proto_dot_cell__limits__2d__pb2
from cartographer.transform.proto import transform_pb2 as cartographer_dot_transform_dot_proto_dot_transform__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+cartographer/mapping/proto/map_limits.proto\x12\x1a\x63\x61rtographer.mapping.proto\x1a/cartographer/mapping/proto/cell_limits_2d.proto\x1a,cartographer/transform/proto/transform.proto\"\x91\x01\n\tMapLimits\x12\x12\n\nresolution\x18\x01 \x01(\x01\x12\x33\n\x03max\x18\x02 \x01(\x0b\x32&.cartographer.transform.proto.Vector2d\x12;\n\x0b\x63\x65ll_limits\x18\x03 \x01(\x0b\x32&.cartographer.mapping.proto.CellLimitsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cartographer.mapping.proto.map_limits_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MAPLIMITS']._serialized_start=171
  _globals['_MAPLIMITS']._serialized_end=316
# @@protoc_insertion_point(module_scope)
