# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/map_builder_options.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cartographer.mapping.proto import pose_graph_options_pb2 as cartographer_dot_mapping_dot_proto_dot_pose__graph__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4cartographer/mapping/proto/map_builder_options.proto\x12\x1a\x63\x61rtographer.mapping.proto\x1a\x33\x63\x61rtographer/mapping/proto/pose_graph_options.proto\"\xe2\x01\n\x11MapBuilderOptions\x12!\n\x19use_trajectory_builder_2d\x18\x01 \x01(\x08\x12!\n\x19use_trajectory_builder_3d\x18\x02 \x01(\x08\x12\x1e\n\x16num_background_threads\x18\x03 \x01(\x05\x12H\n\x12pose_graph_options\x18\x04 \x01(\x0b\x32,.cartographer.mapping.proto.PoseGraphOptions\x12\x1d\n\x15\x63ollate_by_trajectory\x18\x05 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cartographer.mapping.proto.map_builder_options_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MAPBUILDEROPTIONS']._serialized_start=138
  _globals['_MAPBUILDEROPTIONS']._serialized_end=364
# @@protoc_insertion_point(module_scope)
