# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/motion_filter_options.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6cartographer/mapping/proto/motion_filter_options.proto\x12\x1a\x63\x61rtographer.mapping.proto\"g\n\x13MotionFilterOptions\x12\x18\n\x10max_time_seconds\x18\x01 \x01(\x01\x12\x1b\n\x13max_distance_meters\x18\x02 \x01(\x01\x12\x19\n\x11max_angle_radians\x18\x03 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cartographer.mapping.proto.motion_filter_options_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MOTIONFILTEROPTIONS']._serialized_start=86
  _globals['_MOTIONFILTEROPTIONS']._serialized_end=189
# @@protoc_insertion_point(module_scope)
