# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/pose_extrapolator_options.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cartographer.common.proto import ceres_solver_options_pb2 as cartographer_dot_common_dot_proto_dot_ceres__solver__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:cartographer/mapping/proto/pose_extrapolator_options.proto\x12\x1a\x63\x61rtographer.mapping.proto\x1a\x34\x63\x61rtographer/common/proto/ceres_solver_options.proto\"i\n\'ConstantVelocityPoseExtrapolatorOptions\x12!\n\x19imu_gravity_time_constant\x18\x01 \x01(\x01\x12\x1b\n\x13pose_queue_duration\x18\x02 \x01(\x01\"\xe3\x02\n\x1fImuBasedPoseExtrapolatorOptions\x12\x1b\n\x13pose_queue_duration\x18\x01 \x01(\x01\x12\x18\n\x10gravity_constant\x18\x02 \x01(\x01\x12\x1f\n\x17pose_translation_weight\x18\x03 \x01(\x01\x12\x1c\n\x14pose_rotation_weight\x18\x04 \x01(\x01\x12\x1f\n\x17imu_acceleration_weight\x18\x05 \x01(\x01\x12\x1b\n\x13imu_rotation_weight\x18\x06 \x01(\x01\x12\x45\n\x0esolver_options\x18\x07 \x01(\x0b\x32-.cartographer.common.proto.CeresSolverOptions\x12#\n\x1bodometry_translation_weight\x18\x08 \x01(\x01\x12 \n\x18odometry_rotation_weight\x18\t \x01(\x01\"\xe0\x01\n\x17PoseExtrapolatorOptions\x12\x15\n\ruse_imu_based\x18\x01 \x01(\x08\x12^\n\x11\x63onstant_velocity\x18\x02 \x01(\x0b\x32\x43.cartographer.mapping.proto.ConstantVelocityPoseExtrapolatorOptions\x12N\n\timu_based\x18\x03 \x01(\x0b\x32;.cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptionsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cartographer.mapping.proto.pose_extrapolator_options_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CONSTANTVELOCITYPOSEEXTRAPOLATOROPTIONS']._serialized_start=144
  _globals['_CONSTANTVELOCITYPOSEEXTRAPOLATOROPTIONS']._serialized_end=249
  _globals['_IMUBASEDPOSEEXTRAPOLATOROPTIONS']._serialized_start=252
  _globals['_IMUBASEDPOSEEXTRAPOLATOROPTIONS']._serialized_end=607
  _globals['_POSEEXTRAPOLATOROPTIONS']._serialized_start=610
  _globals['_POSEEXTRAPOLATOROPTIONS']._serialized_end=834
# @@protoc_insertion_point(module_scope)
