# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/pose_graph_options.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cartographer.mapping.proto.pose_graph import constraint_builder_options_pb2 as cartographer_dot_mapping_dot_proto_dot_pose__graph_dot_constraint__builder__options__pb2
from cartographer.mapping.proto.pose_graph import optimization_problem_options_pb2 as cartographer_dot_mapping_dot_proto_dot_pose__graph_dot_optimization__problem__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3cartographer/mapping/proto/pose_graph_options.proto\x12\x1a\x63\x61rtographer.mapping.proto\x1a\x46\x63\x61rtographer/mapping/proto/pose_graph/constraint_builder_options.proto\x1aHcartographer/mapping/proto/pose_graph/optimization_problem_options.proto\"\xd3\x05\n\x10PoseGraphOptions\x12\x1e\n\x16optimize_every_n_nodes\x18\x01 \x01(\x05\x12\x64\n\x1a\x63onstraint_builder_options\x18\x03 \x01(\x0b\x32@.cartographer.mapping.constraints.proto.ConstraintBuilderOptions\x12\"\n\x1amatcher_translation_weight\x18\x07 \x01(\x01\x12\x1f\n\x17matcher_rotation_weight\x18\x08 \x01(\x01\x12i\n\x1coptimization_problem_options\x18\x04 \x01(\x0b\x32\x43.cartographer.mapping.optimization.proto.OptimizationProblemOptions\x12 \n\x18max_num_final_iterations\x18\x06 \x01(\x05\x12\x1d\n\x15global_sampling_ratio\x18\x05 \x01(\x01\x12\x1f\n\x17log_residual_histograms\x18\t \x01(\x08\x12\x30\n(global_constraint_search_after_n_seconds\x18\n \x01(\x01\x12w\n\x1eoverlapping_submaps_trimmer_2d\x18\x0b \x01(\x0b\x32O.cartographer.mapping.proto.PoseGraphOptions.OverlappingSubmapsTrimmerOptions2D\x1a|\n\"OverlappingSubmapsTrimmerOptions2D\x12\x1b\n\x13\x66resh_submaps_count\x18\x01 \x01(\x05\x12\x18\n\x10min_covered_area\x18\x02 \x01(\x01\x12\x1f\n\x17min_added_submaps_count\x18\x03 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cartographer.mapping.proto.pose_graph_options_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_POSEGRAPHOPTIONS']._serialized_start=230
  _globals['_POSEGRAPHOPTIONS']._serialized_end=953
  _globals['_POSEGRAPHOPTIONS_OVERLAPPINGSUBMAPSTRIMMEROPTIONS2D']._serialized_start=829
  _globals['_POSEGRAPHOPTIONS_OVERLAPPINGSUBMAPSTRIMMEROPTIONS2D']._serialized_end=953
# @@protoc_insertion_point(module_scope)
