# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/probability_grid_range_data_inserter_options_2d.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nPcartographer/mapping/proto/probability_grid_range_data_inserter_options_2d.proto\x12\x1a\x63\x61rtographer.mapping.proto\"y\n)ProbabilityGridRangeDataInserterOptions2D\x12\x17\n\x0fhit_probability\x18\x01 \x01(\x01\x12\x18\n\x10miss_probability\x18\x02 \x01(\x01\x12\x19\n\x11insert_free_space\x18\x03 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cartographer.mapping.proto.probability_grid_range_data_inserter_options_2d_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_PROBABILITYGRIDRANGEDATAINSERTEROPTIONS2D']._serialized_start=112
  _globals['_PROBABILITYGRIDRANGEDATAINSERTEROPTIONS2D']._serialized_end=233
# @@protoc_insertion_point(module_scope)
