# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/range_data_inserter_options_3d.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?cartographer/mapping/proto/range_data_inserter_options_3d.proto\x12\x1a\x63\x61rtographer.mapping.proto\"\x8b\x01\n\x1aRangeDataInserterOptions3D\x12\x17\n\x0fhit_probability\x18\x01 \x01(\x01\x12\x18\n\x10miss_probability\x18\x02 \x01(\x01\x12\x1d\n\x15num_free_space_voxels\x18\x03 \x01(\x05\x12\x1b\n\x13intensity_threshold\x18\x04 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cartographer.mapping.proto.range_data_inserter_options_3d_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_RANGEDATAINSERTEROPTIONS3D']._serialized_start=96
  _globals['_RANGEDATAINSERTEROPTIONS3D']._serialized_end=235
# @@protoc_insertion_point(module_scope)
