# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/submap_visualization.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cartographer.transform.proto import transform_pb2 as cartographer_dot_transform_dot_proto_dot_transform__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5cartographer/mapping/proto/submap_visualization.proto\x12\x1a\x63\x61rtographer.mapping.proto\x1a,cartographer/transform/proto/transform.proto\"\x95\x02\n\nSubmapList\x12O\n\ntrajectory\x18\x02 \x03(\x0b\x32;.cartographer.mapping.proto.SubmapList.TrajectorySubmapList\x1aZ\n\x0bSubmapEntry\x12\x16\n\x0esubmap_version\x18\x01 \x01(\x05\x12\x33\n\x04pose\x18\x03 \x01(\x0b\x32%.cartographer.transform.proto.Rigid3d\x1aZ\n\x14TrajectorySubmapList\x12\x42\n\x06submap\x18\x01 \x03(\x0b\x32\x32.cartographer.mapping.proto.SubmapList.SubmapEntry\"\xe8\x03\n\x0bSubmapQuery\x12@\n\x07request\x18\x01 \x01(\x0b\x32/.cartographer.mapping.proto.SubmapQuery.Request\x12\x42\n\x08response\x18\x02 \x01(\x0b\x32\x30.cartographer.mapping.proto.SubmapQuery.Response\x1a\x36\n\x07Request\x12\x14\n\x0csubmap_index\x18\x01 \x01(\x05\x12\x15\n\rtrajectory_id\x18\x02 \x01(\x05\x1a\x9a\x02\n\x08Response\x12\x16\n\x0esubmap_version\x18\x02 \x01(\x05\x12P\n\x08textures\x18\n \x03(\x0b\x32>.cartographer.mapping.proto.SubmapQuery.Response.SubmapTexture\x12\x15\n\rerror_message\x18\x08 \x01(\t\x1a\x8c\x01\n\rSubmapTexture\x12\r\n\x05\x63\x65lls\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x12\n\nresolution\x18\x04 \x01(\x01\x12\x39\n\nslice_pose\x18\x05 \x01(\x0b\x32%.cartographer.transform.proto.Rigid3db\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cartographer.mapping.proto.submap_visualization_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SUBMAPLIST']._serialized_start=132
  _globals['_SUBMAPLIST']._serialized_end=409
  _globals['_SUBMAPLIST_SUBMAPENTRY']._serialized_start=227
  _globals['_SUBMAPLIST_SUBMAPENTRY']._serialized_end=317
  _globals['_SUBMAPLIST_TRAJECTORYSUBMAPLIST']._serialized_start=319
  _globals['_SUBMAPLIST_TRAJECTORYSUBMAPLIST']._serialized_end=409
  _globals['_SUBMAPQUERY']._serialized_start=412
  _globals['_SUBMAPQUERY']._serialized_end=900
  _globals['_SUBMAPQUERY_REQUEST']._serialized_start=561
  _globals['_SUBMAPQUERY_REQUEST']._serialized_end=615
  _globals['_SUBMAPQUERY_RESPONSE']._serialized_start=618
  _globals['_SUBMAPQUERY_RESPONSE']._serialized_end=900
  _globals['_SUBMAPQUERY_RESPONSE_SUBMAPTEXTURE']._serialized_start=760
  _globals['_SUBMAPQUERY_RESPONSE_SUBMAPTEXTURE']._serialized_end=900
# @@protoc_insertion_point(module_scope)
