# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/submaps_options_3d.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cartographer.mapping.proto import range_data_inserter_options_3d_pb2 as cartographer_dot_mapping_dot_proto_dot_range__data__inserter__options__3d__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3cartographer/mapping/proto/submaps_options_3d.proto\x12\x1a\x63\x61rtographer.mapping.proto\x1a?cartographer/mapping/proto/range_data_inserter_options_3d.proto\"\xdb\x01\n\x10SubmapsOptions3D\x12\x17\n\x0fhigh_resolution\x18\x01 \x01(\x01\x12!\n\x19high_resolution_max_range\x18\x04 \x01(\x01\x12\x16\n\x0elow_resolution\x18\x05 \x01(\x01\x12\x16\n\x0enum_range_data\x18\x02 \x01(\x05\x12[\n\x1brange_data_inserter_options\x18\x03 \x01(\x0b\x32\x36.cartographer.mapping.proto.RangeDataInserterOptions3Db\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cartographer.mapping.proto.submaps_options_3d_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SUBMAPSOPTIONS3D']._serialized_start=149
  _globals['_SUBMAPSOPTIONS3D']._serialized_end=368
# @@protoc_insertion_point(module_scope)
