# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/submap.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cartographer.mapping.proto import grid_2d_pb2 as cartographer_dot_mapping_dot_proto_dot_grid__2d__pb2
from cartographer.mapping.proto import hybrid_grid_pb2 as cartographer_dot_mapping_dot_proto_dot_hybrid__grid__pb2
from cartographer.transform.proto import transform_pb2 as cartographer_dot_transform_dot_proto_dot_transform__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'cartographer/mapping/proto/submap.proto\x12\x1a\x63\x61rtographer.mapping.proto\x1a(cartographer/mapping/proto/grid_2d.proto\x1a,cartographer/mapping/proto/hybrid_grid.proto\x1a,cartographer/transform/proto/transform.proto\"\xa1\x01\n\x08Submap2D\x12\x39\n\nlocal_pose\x18\x01 \x01(\x0b\x32%.cartographer.transform.proto.Rigid3d\x12\x16\n\x0enum_range_data\x18\x02 \x01(\x05\x12\x10\n\x08\x66inished\x18\x03 \x01(\x08\x12\x30\n\x04grid\x18\x04 \x01(\x0b\x32\".cartographer.mapping.proto.Grid2D\"\xb3\x02\n\x08Submap3D\x12\x39\n\nlocal_pose\x18\x01 \x01(\x0b\x32%.cartographer.transform.proto.Rigid3d\x12\x16\n\x0enum_range_data\x18\x02 \x01(\x05\x12\x10\n\x08\x66inished\x18\x03 \x01(\x08\x12K\n\x1bhigh_resolution_hybrid_grid\x18\x04 \x01(\x0b\x32&.cartographer.mapping.proto.HybridGrid\x12J\n\x1alow_resolution_hybrid_grid\x18\x05 \x01(\x0b\x32&.cartographer.mapping.proto.HybridGrid\x12)\n!rotational_scan_matcher_histogram\x18\x06 \x03(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cartographer.mapping.proto.submap_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SUBMAP2D']._serialized_start=206
  _globals['_SUBMAP2D']._serialized_end=367
  _globals['_SUBMAP3D']._serialized_start=370
  _globals['_SUBMAP3D']._serialized_end=677
# @@protoc_insertion_point(module_scope)
