# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/tsdf_2d.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(cartographer/mapping/proto/tsdf_2d.proto\x12\x1a\x63\x61rtographer.mapping.proto\"O\n\x06TSDF2D\x12\x1b\n\x13truncation_distance\x18\x01 \x01(\x02\x12\x12\n\nmax_weight\x18\x02 \x01(\x02\x12\x14\n\x0cweight_cells\x18\x03 \x03(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cartographer.mapping.proto.tsdf_2d_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TSDF2D']._serialized_start=72
  _globals['_TSDF2D']._serialized_end=151
# @@protoc_insertion_point(module_scope)
