# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/tsdf_range_data_inserter_options_2d.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cartographer.mapping.proto import normal_estimation_options_2d_pb2 as cartographer_dot_mapping_dot_proto_dot_normal__estimation__options__2d__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nDcartographer/mapping/proto/tsdf_range_data_inserter_options_2d.proto\x12\x1a\x63\x61rtographer.mapping.proto\x1a=cartographer/mapping/proto/normal_estimation_options_2d.proto\"\x9b\x03\n\x1eTSDFRangeDataInserterOptions2D\x12\x1b\n\x13truncation_distance\x18\x01 \x01(\x01\x12\x16\n\x0emaximum_weight\x18\x02 \x01(\x01\x12\x19\n\x11update_free_space\x18\x03 \x01(\x08\x12X\n\x19normal_estimation_options\x18\x04 \x01(\x0b\x32\x35.cartographer.mapping.proto.NormalEstimationOptions2D\x12+\n#project_sdf_distance_to_scan_normal\x18\x05 \x01(\x08\x12$\n\x1cupdate_weight_range_exponent\x18\x06 \x01(\x05\x12?\n7update_weight_angle_scan_normal_to_ray_kernel_bandwidth\x18\x07 \x01(\x01\x12;\n3update_weight_distance_cell_to_hit_kernel_bandwidth\x18\x08 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cartographer.mapping.proto.tsdf_range_data_inserter_options_2d_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TSDFRANGEDATAINSERTEROPTIONS2D']._serialized_start=164
  _globals['_TSDFRANGEDATAINSERTEROPTIONS2D']._serialized_end=575
# @@protoc_insertion_point(module_scope)
