# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/transform/proto/timestamped_transform.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cartographer.transform.proto import transform_pb2 as cartographer_dot_transform_dot_proto_dot_transform__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8cartographer/transform/proto/timestamped_transform.proto\x12\x1c\x63\x61rtographer.transform.proto\x1a,cartographer/transform/proto/transform.proto\"^\n\x14TimestampedTransform\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\x38\n\ttransform\x18\x02 \x01(\x0b\x32%.cartographer.transform.proto.Rigid3db\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cartographer.transform.proto.timestamped_transform_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TIMESTAMPEDTRANSFORM']._serialized_start=136
  _globals['_TIMESTAMPEDTRANSFORM']._serialized_end=230
# @@protoc_insertion_point(module_scope)
