# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/transform/proto/transform.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,cartographer/transform/proto/transform.proto\x12\x1c\x63\x61rtographer.transform.proto\" \n\x08Vector2d\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\" \n\x08Vector2f\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"+\n\x08Vector3d\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"+\n\x08Vector3f\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"6\n\x08Vector4f\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\t\n\x01t\x18\x04 \x01(\x02\"9\n\x0bQuaterniond\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\t\n\x01w\x18\x04 \x01(\x01\"9\n\x0bQuaternionf\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\t\n\x01w\x18\x04 \x01(\x02\"X\n\x07Rigid2d\x12;\n\x0btranslation\x18\x01 \x01(\x0b\x32&.cartographer.transform.proto.Vector2d\x12\x10\n\x08rotation\x18\x02 \x01(\x01\"X\n\x07Rigid2f\x12;\n\x0btranslation\x18\x01 \x01(\x0b\x32&.cartographer.transform.proto.Vector2f\x12\x10\n\x08rotation\x18\x02 \x01(\x02\"\x83\x01\n\x07Rigid3d\x12;\n\x0btranslation\x18\x01 \x01(\x0b\x32&.cartographer.transform.proto.Vector3d\x12;\n\x08rotation\x18\x02 \x01(\x0b\x32).cartographer.transform.proto.Quaterniond\"\x83\x01\n\x07Rigid3f\x12;\n\x0btranslation\x18\x01 \x01(\x0b\x32&.cartographer.transform.proto.Vector3f\x12;\n\x08rotation\x18\x02 \x01(\x0b\x32).cartographer.transform.proto.Quaternionfb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cartographer.transform.proto.transform_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_VECTOR2D']._serialized_start=78
  _globals['_VECTOR2D']._serialized_end=110
  _globals['_VECTOR2F']._serialized_start=112
  _globals['_VECTOR2F']._serialized_end=144
  _globals['_VECTOR3D']._serialized_start=146
  _globals['_VECTOR3D']._serialized_end=189
  _globals['_VECTOR3F']._serialized_start=191
  _globals['_VECTOR3F']._serialized_end=234
  _globals['_VECTOR4F']._serialized_start=236
  _globals['_VECTOR4F']._serialized_end=290
  _globals['_QUATERNIOND']._serialized_start=292
  _globals['_QUATERNIOND']._serialized_end=349
  _globals['_QUATERNIONF']._serialized_start=351
  _globals['_QUATERNIONF']._serialized_end=408
  _globals['_RIGID2D']._serialized_start=410
  _globals['_RIGID2D']._serialized_end=498
  _globals['_RIGID2F']._serialized_start=500
  _globals['_RIGID2F']._serialized_end=588
  _globals['_RIGID3D']._serialized_start=591
  _globals['_RIGID3D']._serialized_end=722
  _globals['_RIGID3F']._serialized_start=725
  _globals['_RIGID3F']._serialized_end=856
# @@protoc_insertion_point(module_scope)
